### PR TITLE
User socket options

### PR DESCRIPTION
**Pull request by marcusbirkin**
Allow the use of a user supplied sockets options
Updated documentation explaining use, and providing example IPv6 usage

### CODE REVIEW

**Comment by JaredSartin** [comment]
GitHub says this PR is a draft. Happy to merge when complete

**Comment by marcusbirkin** [comment]
This is just the first part, but works as-is. There is some extra work to add to this.
_If_ the user's platform has some form of async timer, I want to allow the query to be non-blocking.

**Comment by JaredSartin** [comment]
Awesome! Happy to wait for that

**Comment by marcusbirkin** [comment]
There is also a good chance that this will also create a merge confict with #4, I would recommend that is merged in (if approved!) and I'll rebase this branch

**Comment by JaredSartin** [comment]
Merged #4

**Comment by marcusbirkin** [comment]
Rebased on master branch
Add ability for user supplied async timer operations with a non-blocking query function
Updated documentation

**Pull request merged**
